### ISSUE TITLE
Add healthcheck for APC MQTT subscriptions

### ISSUE THREAD

**Issue by mjaakko** [HSLdevcom/transitdata#243]
`mqtt-pulsar-gateway` that subscribes to APC MQTT feed seems to crash every now and then:

```
org.apache.pulsar.client.api.PulsarClientException$TimeoutException: Could not send message to broker within given timeout
	at org.apache.pulsar.client.impl.ProducerImpl.run(ProducerImpl.java:1160)
	at org.apache.pulsar.shade.io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:682)
	at org.apache.pulsar.shade.io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:757)
	at org.apache.pulsar.shade.io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:485)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Add healthcheck to fix this

**Comment by mjaakko** [comment]
Healthcheck was implemented, but not enabled. This has been fixed
