### ISSUE TITLE
Fix metro cancellations 

### ISSUE THREAD

**Issue by mjaakko** [HSLdevcom/transitdata#46]
PRs:
https://github.com/HSLdevcom/transitdata-metro-ats-parser/pull/9 https://github.com/HSLdevcom/transitdata-metro-ats-cancellation-source/pull/4
https://github.com/HSLdevcom/transitdata-stop-estimates/pull/17 

Metro cancellations are currently producing errors:

```
com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: metro_rows[0].row_progress, metro_rows[1].row_progress, metro_rows[2].row_progress, metro_rows[3].row_progress, metro_rows[4].row_progress, metro_rows[5].row_progress, metro_rows[6].row_progress, metro_rows[7].row_progress, metro_rows[8].row_progress, metro_rows[9].row_progress, metro_rows[10].row_progress, metro_rows[11].row_progress, metro_rows[12].row_progress, metro_rows[13].row_progress, metro_rows[14].row_progress, metro_rows[15].row_progress, metro_rows[16].row_progress, metro_rows[17].row_progress, metro_rows[18].row_progress
    at com.google.protobuf.UninitializedMessageException.asInvalidProtocolBufferException(UninitializedMessageException.java:81)
    at com.google.protobuf.AbstractParser.checkMessageInitialized(AbstractParser.java:72)
    at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:196)
    at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
    at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:214)
    at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
    at fi.hsl.common.transitdata.proto.MetroAtsProtos$MetroEstimate.parseFrom(MetroAtsProtos.java:3592)
    at fi.hsl.transitdata.metro.ats.MetroCancellationFactory.toTripCancellation(MetroCancellationFactory.java:46)
    at fi.hsl.transitdata.metro.ats.MetroCancellationFactory.toTripCancellation(MetroCancellationFactory.java:36)
    at fi.hsl.transitdata.metro.ats.MessageHandler.handleMessage(MessageHandler.java:28)
    at fi.hsl.common.pulsar.PulsarApplication.launchWithHandler(PulsarApplication.java:198)
    at fi.hsl.transitdata.metro.ats.Main.main(Main.java:116)
```

**Comment by samijuhani** [comment]
@hellej fyi. This needs to be tested also. I will do it.
